inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - '**/*.gemspec'
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - 'test/fixtures/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes
